/*
    Auto-generated by: https://github.com/pmndrs/gltfjsx
    Command: npx gltfjsx@6.5.0 react.glb -T
    Author: xenadus (https://sketchfab.com/xenadus)
    License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
    Source: https://sketchfab.com/3d-models/react-logo-76174ceeba96487f9863f974636f641e
*/

import { Float, useGLTF } from '@react-three/drei';

/**
 * The ReactLogo component.
 * This component renders the React logo in 3D.
 * The logo is loaded from the 'models/react.glb' file.
 * The file is preloaded by the useGLTF.preload function.
 * The useGLTF hook is used to load the logo's geometry and materials.
 * The geometry and materials are then used to render the logo as a mesh.
 * The mesh is wrapped in a Float component to give it a floating effect.
 * The group that wraps the mesh is positioned, scaled and rotated to place
 * the logo in the correct position in the scene.
 * The Float component is used to give the logo a floating effect.
 * It takes a floatIntensity prop which controls how intense the floating effect is.
 * The component also takes a position, scale and rotation prop which can be used
 * to position, scale and rotate the logo in the scene.
 * The props are passed through to the group that wraps the mesh.
 * The component returns a JSX element that renders the logo.
 */
const ReactLogo = (props) : JSX.Element  => {
  const { nodes, materials } = useGLTF('models/react.glb');

  return (
    <Float floatIntensity={1}>
      <group position={[8, 8, 0]} scale={0.3} {...props} dispose={null}>
        <mesh
          geometry={nodes['React-Logo_Material002_0'].geometry}
          material={materials['Material.002']}
          position={[0, 0.079, 0.181]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.392, 0.392, 0.527]}
        />
      </group>
    </Float>
  );
};

/**
 * Preload the 'models/react.glb' file.
 * This ensures that the file is loaded before the component is rendered.
 * The file is loaded by the useGLTF hook.
 */
useGLTF.preload('models/react.glb');

/**
 * Export the ReactLogo component.
 * The component can now be imported and used in other components.
 */
export default ReactLogo;

